### PR TITLE
fix: remove helmet user stories

### PR DESCRIPTION
**Pull request by moT01**
Remove helmet user stories from boilerplate.

See https://github.com/freeCodeCamp/freeCodeCamp/issues/39435

### CODE REVIEW

**Review by naomi-lgbt — APPROVED** [review]
LGTM! 🥳

**Review by ShaunSHamilton — DISMISSED** [review]
LGTM 👍

**Comment by ShaunSHamilton** [comment]
@moT01 Do you want to remove the third line from the README.md in this PR to?

**Comment by moT01** [comment]
Nice catch @Sky020 - yea, we shouldn't need that.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍  Thank you, Tom.

**Comment by ShaunSHamilton** [comment]
Thank you, for your contributions! 👍

We are happy to accept these changes. 🎉

**Pull request merged**
