### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Enikol**
Both PUT and DELETE forms had the same id "testForm2", and DELETE form didn't work because of that; I changed it to "testForm3", now everything works like it's supposed to.

### CODE REVIEW

**Comment by rudolphh** [comment]
+1

**Comment by lieberscott** [comment]
+1

**Comment by DaniloNovakovic** [comment]
this should resolve #2

**Comment by scissorsneedfoodtoo** [comment]
Thanks for your patience and for this fix @Enikol. I can confirm that this is an issue in the boilerplate, but was fixed in the solution sometime in the past. Everything LGTM :+1: :+1:

**Pull request merged**
